language: java
jdk: oraclejdk8
sudo: required

addons:
  apt:
    packages:
    - glpk

env:
  - DISPLAY=:99.0

before_install:
  - sh -e /etc/init.d/xvfb start

install:
  true

script:
  mvn clean package

after_success:
  echo "Build successful. Awesome!"

after_failure:
  echo "Build finished with errors. Bollocks!"

notifications:
  email: true