language: java
jdk: oraclejdk8
sudo: required

addons:
  apt:
    packages:
    - glpk

before-script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

install:
  true

script:
  mvn clean package

after_success:
  echo $SUCCESSMESSAGE

after_failure:
  echo $ERRORMESSAGE

notifications:
  email: true