language: java
jdk: oraclejdk8
sudo: required

before_install:
  chmod +x maven_script.sh && chmod +x solvers.sh

install:
  bash solvers.sh

script:
  bash maven_script.sh

after_success:
  echo $SUCCESSMESSAGE

after_failure:
  echo $ERRORMESSAGE

notifications:
  email: false